### ISSUE TITLE
Train pb on WaveRNN

### ISSUE THREAD

**Issue by VoxFurem** [Tomiinek/Multilingual_Text_to_Speech#40]
Hello Tomáš,

I have a problem when I try to train my dataset with WaveRNN.
It returns me this error:

```
voxfurem@cc:~/nvme/src/WaveRNN$ python train_wavernn.py --force
Initialising Model...
Trainable Parameters: 4.744M
Path=/media/nvme/src/WaveRNN/dataset
Batch size=32
Paths = <utils.paths.Paths object at 0x7fab0adebca0>
NUM EXIST = 3
Restoring from latest checkpoint...
Loading latest weights: /media/nvme/src/WaveRNN/checkpoints/css_raw.wavernn/latest_weights.pyt
Loading latest optimizer state: /media/nvme/src/WaveRNN/checkpoints/css_raw.wavernn/latest_optim.pyt
| Epoch: 1/147059 (1/68) | Loss: 6.9385 | LR: 0.0010 | 1.3 steps/s | Step: 0k | Traceback (most recent call last):
  File "train_wavernn.py", line 136, in <module>
    voc_train_loop(paths, voc_model, loss_func, optimizer, scheduler, train_set, test_set, total_steps)
  File "train_wavernn.py", line 31, in voc_train_loop
    for i, (x, y, m) in enumerate(train_set, 1):
  File "/home/voxfurem/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/voxfurem/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/voxfurem/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/voxfurem/.local/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/voxfurem/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/voxfurem/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/media/nvme/src/WaveRNN/utils/dataset.py", line 109, in collate_vocoder
    labels = np.stack(labels).astype(np.int64)
  File "/home/voxfurem/.local/lib/python3.8/site-packages/numpy/core/shape_base.py", line 416, in stack
    raise ValueError('all input arrays must have the same shape')
**ValueError: all input arrays must have the same shape**
```

I spend some hours to try to understand this error, I develop a system to seach the file which can be the cause, I restart with another voice package, etc... but I failed to find a solution.

Do you have any idea of the root cause for this problem ?

Thanks in advance

**Comment by Tomiinek** [comment]
Hi @VoxFurem 

What code are you running?
Have you made any changes?
What data do you use?

The cause is a shape mismatch, I would guess you somehow messed up preprocessing of the training files.
Try printing the shapes and think about what shapes are expected and what could cause the mismatch. The training fails early on the very first batch of data, so it is not something "hidden". 

I cannot tell you what the problem is just from this message.
