### ISSUE TITLE
Basic workflow on how to train the model and synthesize it? When to use the datasets. Help! 🙏

### ISSUE THREAD

**Issue by krigeta** [Tomiinek/Multilingual_Text_to_Speech#48]
Hello, I am struggling to get an idea of the workflow of this awesome project.

As you mentioned in the readme that we have to use the comvoi.zip and for now I am using the css10 dataset for three languages.
everything is set up but may somebody please explain a workflow on how and why to fix things to train the model and then synthesize it using the WaveRNN.

I have a lot of questions but let's first see if someone will guide me for the initial steps.

**Comment by Tomiinek** [comment]
Please have a look at some older closed issues.

You have to:
- Train a model that converts text to spectrograms (MTS) -- use CSS10 and CommonVoice
- Train a model that converts spectrograms to audio (WaveRNN) -- use CSS10
- Use the models together to synthesize your new audios

**Comment by krigeta** [comment]
Yes I am going through all of them closed ones as well. So as far as I am understanding that:

1) I have to follow the readme steps to train a tacotron 2 model in x-languages? (but I am confused on why we are using the comvoice when we already using the CSS10 dataset?)

2) btw Where to find the steps on how to train the WaveRNN?

3) then use those models in collab to get the desired output?

4) in the collab we can see that we have different ids for speakers to synthesis the audio but from where do we get those ids?

Sorry for asking too much questions but I am very tensed because I am not able to make it run but hope will able to do that with the help of you guidance.

**Comment by Tomiinek** [comment]
1. Because CSS10 contains just one speaker for each language and it is not enough.
2. In the WaveRNN repository
3. I think CPU is ok during synthesis.
4. The `ids` come from your training data and the `id-speaker` assignment you choose. You cannot synthesize voices you have never heard.

**Comment by krigeta** [comment]
Hello,

![Errors](https://user-images.githubusercontent.com/75309361/114169241-ed242580-994e-11eb-9ac9-71b89edfcb26.png)

In this image I got some errors and some questions, may you please look into them?

**Comment by Tomiinek** [comment]
- The structure is ok
- The two created folders will contain newly created processed spectrograms. Yes they are.
- No, it is not ok.
- Yes it is, you should open `train.txt` and `val.txt` and modify them so that they contain only entries for the languages you want.

Btw your disk usage (5.45GB) is hitting the max value so it will likely fail during the spectrogram creation anyway. They take some space.

**Comment by krigeta** [comment]
Hello @Tomiinek ,
• Finally, I edit the Train.txt and val.txt acc. to my needs. (btw what va;.txt(validation txt is used for and what values are written in it?))

So I got a new error about the values
```
Traceback (most recent call last):
File "prepare_css_spectrograms.py", line 57, in <module>
idx, s, l, a, _, _, raw_text, ph = i
ValueError: not enough values to unpack (expected 8, got 5)
```
• How can I fix this error?

• <a href="https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/fe23932188d8ada7a23cabc6f3e367d2e618f5ab/dataset/dataset.py#L193">TextToSpeechDataset.create_meta_file</a> This one is also for generating spectograms? , if yes then what is the difference between this and the prepare_css_spectrograms.py?

BTW about the storage issue, i am glad you point it out but now I manage to get around 69gb of total so, after getting all of the datasets (css10[for now using only four] + comvoice) there is still 49GB of space left so hope it will work.

• Can I able to train it offline in Windows 10? (or should i go for ubuntu?)
RTX 2060 8GB, 16GB ram and AMD ryzen 2700 8 cores CPU, these are the specs for offline?

Please help me sir

**Comment by krigeta** [comment]
Hello, @leijue222 <a href="https://github.com/Tomiinek/Multilingual_Text_to_Speech/issues/27#issuecomment-719874655">what changes you made to the file, I am running prepare_css_spectrograms.py as it is and it is giving me this error.</a>

**Comment by zj19980122** [comment]
> Hello @Tomiinek and @zj19980122 ,
> • Finally, I edit the Train.txt and val.txt acc. to my needs. (btw what va;.txt(validation txt is used for and what values are written in it?))
> 
> So I got a new error about the values
> 
> ```
> Traceback (most recent call last):
> File "prepare_css_spectrograms.py", line 57, in <module>
> idx, s, l, a, _, _, raw_text, ph = i
> ValueError: not enough values to unpack (expected 8, got 5)
> ```
> 
> • How can I fix this error? because the value for 4,5 place has "_" in the script and in the train.txt and val.txt it has only blank space like
> 
> 062735|spanish|spanish|spanish/batalla_arapiles/batalla_arapiles_3040.wav **|||** Poco a poco fui perdiéndole el miedo: me causaba cierto respeto; pero amarle. ¡eso imposible!|
> do I have to type them manually? and what abouut the ph = i, will it get the value from the for loop or any other value?
> 
> • [TextToSpeechDataset.create_meta_file](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/fe23932188d8ada7a23cabc6f3e367d2e618f5ab/dataset/dataset.py#L193) This one is also for generating spectograms? , if yes then what is the difference between this and the prepare_css_spectrograms.py?
> 
> BTW about the storage issue, i am glad you point it out but now I manage to get around 69gb of total so, after getting all of the datasets (css10[for now using only four] + comvoice) there is still 49GB of space left so hope it will work.
> 
> • Can I able to train it offline in Windows 10? (or should i go for ubuntu?)
> RTX 2060 8GB, 16GB ram and AMD ryzen 2700 8 cores CPU, these are the specs for offline?
> 
> Please help me sir

Hello again. For the val.txt, you can try to use sklearn package to automatically split the dataset into train.txt and val.txt. The further detail you can search on google.

`from sklearn.model_selection import train_test_split`

This error is mostly because your form of metadata is wrong. Please check the file carefully and make sure you have 7 **"|"** in the line of data(Since you only can split into 5 parts so it raises error). The form of metadata you can find in our previous discussion.

**Comment by krigeta** [comment]
>Hello again. For the val.txt, you can try to use sklearn package to automatically split the dataset into train.txt and val.txt. The further detail you can search on google.
from sklearn.model_selection import train_test_split

Actually, I was saying what the function of the val.txt file? and thanks for the sklearn package so by using this package I can able to split the data, right? but what would be the input file for that?

>This error is mostly because your form of metadata is wrong. Please check the file carefully and make sure you have 7 "|" in the line of data(Since you only can split into 5 parts so it raises an error). The form of metadata you can find in our previous discussion.

Yup I knew it is because of the wrong meta-data but as you said the train.txt and val.txt file contains the 7 "|", but the place of linear spectogram and spectrogram in black like this line below: 

>062735|spanish|spanish|spanish/batalla_arapiles/batalla_arapiles_3040.wav ||| Poco a poco fui perdiéndole el miedo: me causaba cierto respeto; pero amarle. ¡eso imposible!|

Do I have to add the path for the linear spectrogram and spectrogram manually one by one in the train.txt or val.txt?

And what about the <a href="https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/fe23932188d8ada7a23cabc6f3e367d2e618f5ab/dataset/dataset.py#L193">TextToSpeechDataset.create_meta_file</a>, it is also to generate the spectograms? if yes then why we have two scripts to do the same thing? and what changes should we make to this and when this function will be called? sorry for the lot of questions.  🙏

**Comment by zj19980122** [comment]
> > Hello again. For the val.txt, you can try to use sklearn package to automatically split the dataset into train.txt and val.txt. The further detail you can search on google.
> > from sklearn.model_selection import train_test_split
> 
> Actually, I was saying what the function of the val.txt file? and thanks for the sklearn package so by using this package I can able to split the data, right? but what would be the input file for that?
> 
> > This error is mostly because your form of metadata is wrong. Please check the file carefully and make sure you have 7 "|" in the line of data(Since you only can split into 5 parts so it raises an error). The form of metadata you can find in our previous discussion.
> 
> Yup I knew it is because of the wrong meta-data but as you said the train.txt and val.txt file contains the 7 "|", but the place of linear spectogram and spectrogram in black like this line below:
> 
> > 062735|spanish|spanish|spanish/batalla_arapiles/batalla_arapiles_3040.wav ||| Poco a poco fui perdiéndole el miedo: me causaba cierto respeto; pero amarle. ¡eso imposible!|
> 
> Do I have to add the path for the linear spectrogram and spectrogram manually one by one in the train.txt or val.txt?
> 
> And what about the [TextToSpeechDataset.create_meta_file](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/fe23932188d8ada7a23cabc6f3e367d2e618f5ab/dataset/dataset.py#L193), it is also to generate the spectograms? if yes then why we have two scripts to do the same thing? and what changes should we make to this and when this function will be called? sorry for the lot of questions. 🙏

val.txt will help you know whether things go well during training process. And you don't need to worry about the input file. Just use all your dataset to generate one txt file and then split it into train.txt and val.txt. 

This form of data seems good. The prepare_css_spectrograms.py will automatically fill the path of linear spectrogram and spectrogram. You can read the code to understand how it works.

For other questions maybe the author can help you. 😄

**Comment by krigeta** [comment]
>val.txt will help you know whether things go well during the training process. And you don't need to worry about the input file. Just use all your dataset to generate one txt file and then split it into train.txt and val.txt.

so means first I have to make a txt file manually by writing line by line then by using the sklearn package it will convert that text file into train.txt and val.txt, right? or is there any other automatic method to generate txt files?(that would be so awesome)

>This form of data seems good. The prepare_css_spectrograms.py will automatically fill the path of linear spectrogram and spectrogram. You can read the code to understand how it works.

but still whenever i am running the prepare_css_spectrograms.py by using the txt files with the format above it is still throwing the error. :(

>For other questions maybe the author can help you. 😄

Waiting for his reply as well

**Comment by krigeta** [comment]
Finally able to run the prepare_css_spectrograms.py successfully, Actually there are few mistakes in the train.txt for css10 dataset.

So may somebody please tell me about this and how to run it 

<a href="https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/fe23932188d8ada7a23cabc6f3e367d2e618f5ab/dataset/dataset.py#L193">TextToSpeechDataset.create_meta_file</a>

**Comment by Tomiinek** [comment]
Hello, you can use both scripts. They should do almost the same things, `prepare_css_spectrograms.py` is a light version that I prepared for easy start with the original datasets.

You can run `TextToSpeechDataset.create_meta_file` as any other python function, just open python console, type `from dataset.dataset import create_meta_file` and use it.

**Comment by krigeta** [comment]
Hello, sorry for replying late, having some health issues. So I tried 3 ways and getting errors, here are the images of errors.

![Screenshot (2)](https://user-images.githubusercontent.com/75309361/116792346-b2d91e80-aadd-11eb-88e4-3d16bbc39143.png)
one
![Screenshot (3)](https://user-images.githubusercontent.com/75309361/116792348-b40a4b80-aadd-11eb-9a16-2106874d3038.png)
two
![Screenshot (4)](https://user-images.githubusercontent.com/75309361/116792349-b4a2e200-aadd-11eb-9eff-a182abe60e6c.png)
three

Please correct me where I am wrong.

**Comment by krigeta** [comment]
hello @Tomiinek sir, any update?

**Comment by Tomiinek** [comment]
Hello,

`TextToSpeechDataset.create_meta_file` is a function with arguments, and so you have to provide values for all them in order to call the function. The arguments are thoroughly described in the function definition:

https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/caa65277b914346d12a04cdbee799585ba1e48ce/dataset/dataset.py#L193-L214

Please, have a look at some [python tutorials](https://docs.python.org/3/tutorial/index.html) prior opening issues :pray:

**Comment by krigeta** [comment]
Hello, Yup did it already and thats why I opened a new issue(sorry for that) I am using these values right now:

```
dataset_name = "my_common_voice"
dataset_root_dir = "/Multilingual_Text_to_Speech/data/comvoi_clean"
output_metafile_name = "meta"
audio_sample_rate = 22050
num_fft_freqs = 1102
```

is `num_fft_freqs = 1102` is correct or if not then from where can I get to know about it?

I am just stuck at the issue #51 

and yes I am watching the python tutorials but because I am recovering from covid-19, my speed is slow. hope you understand.

**Comment by Tomiinek** [comment]
Ok great, `num_fft_freqs=1102` is ok. 
If you cannot make the phonemizer working, you can simply pass `phonemes=False` into the `create_meta_file` function and it will skip the conversion into phonemes. Grapheme input should be be ok together with the generated model. I used phonemes only in my initial experiments.

**Comment by krigeta** [comment]
Okay, so what installing commands exactly you were using for **espeak**, **epitran** and **phonemizer** when you were experimenting with phonemes?

like `!pip install espeak-ng`

```
ERROR: Could not find a version that satisfies the requirement espeak-ng (from versions: none)
ERROR: No matching distribution found for espeak-ng

```
`!pip install espeak`

```
ERROR: Could not find a version that satisfies the requirement espeak (from versions: none)
ERROR: No matching distribution found for espeak
```


giving me these above error and I am simple using requirements.txt to install the packages.

**Comment by Tomiinek** [comment]
**Short answer:** I don't know. 

**Long answer:** The `phonemizer` is in `requirements.txt`, `pip install phonemizer` works. If you do not have the `espeak` backend, install it as suggested in phonemizer's [installation instructions](https://pypi.org/project/phonemizer/), e.g. `sudo apt-get install festival espeak-ng mbrola` on Ubuntu. 

**Suggestion:** Don't ask me how to install it on Windows. Read the messages of the errors you are reffering to.  If it says that the package does not exist, the package does not exist. If it says that a function is not defined, you have to define it. If it says that some arguments are missing, you have to provide them. If it says that it cannot open a file, check if it exists.

**Comment by krigeta** [comment]
Hello,
Before asking you questions I really try my best to solve them on my own or by asking someone else but in the end you are the only person who has the exact knowledge of what is going on because it's your awesome project.

I know my queries are on a beginner level and it is irritating you and I am feeling sorry for that but I believe that asking is better than nothing and I am **setting up it in Google colab** so maybe it can help but let's see will am I able to make something which can help others as well so they can just come and train their own models easily.

Last Query: May I ask questions in the future or not? because I don't want to bother you.

Thank you
