### ISSUE TITLE
When I try to train it, I got the following error: 

### ISSUE THREAD

**Issue by AndreiMunteanu8** [Tomiinek/Multilingual_Text_to_Speech#79]
AttributeError: Caught AttributeError in DataLoader worker process 0.

  if is_mel: return (S - hp.mel_normalize_mean) / hp.mel_normalize_variance
AttributeError: type object 'Params' has no attribute 'mel_normalize_mean'

As I see in the code, those attributes aren't in the parms class.

**Comment by Tomiinek** [comment]
Yeah, because `hp.mel_normalize_mean` is a 80-dimensional float vector, calculated on-the-fly.
See https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/fe23932188d8ada7a23cabc6f3e367d2e618f5ab/train.py#L248

**Comment by AndreiMunteanu8** [comment]
Yup, I solved it but I still run into this error when I try to train it. 
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding).

Unfortunately, torch 1.3.0 is not available anymore so I tried torch 1.2.0 and torch 1.4.0 instead without success.

**Comment by Tomiinek** [comment]
Could you please share the whole call stack?

**Comment by AndreiMunteanu8** [comment]
Yes



Traceback (most recent call last):
  File "train.py", line 296, in <module>
    train(args.logging_start, epoch, train_data, model, criterion, optimizer)
  File "train.py", line 63, in train
    post_pred, pre_pred, stop_pred, alignment, spkrs_pred, enc_output = model(src, src_len, trg_mel, trg_len, spkrs, langs, tf)
  File "C:\Work\envs\tacotron\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\TACOTRON MODEL\Multilingual Tacotrtoon\Multilingual_Text_to_Speech-master\modules\tacotron2.py", line 373, in forward
    decoded = self._decoder(encoded, text_length, target, teacher_forcing_ratio, speakers, languages)
  File "C:\Work\envs\tacotron\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\TACOTRON MODEL\Multilingual Tacotrtoon\Multilingual_Text_to_Speech-master\modules\tacotron2.py", line 214, in forward
    return self._decode(encoded_input, mask, target, teacher_forcing_ratio, speaker, language)
  File "D:\TACOTRON MODEL\Multilingual Tacotrtoon\Multilingual_Text_to_Speech-master\modules\tacotron2.py", line 159, in _decode
    encoded_input = self._add_conditional_embedding(encoded_input, self._speaker_embedding, speaker)
  File "D:\TACOTRON MODEL\Multilingual Tacotrtoon\Multilingual_Text_to_Speech-master\modules\tacotron2.py", line 145, in _add_conditional_embedding
    embedded = layer(encoded if condition is None else condition)
  File "C:\Work\envs\tacotron\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Work\envs\tacotron\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Work\envs\tacotron\lib\site-packages\torch\nn\functional.py", line 1467, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)

**Comment by b-rania** [comment]
I get the same error as in the initial comment. It seems that the attributes is not passed between the files when normalizing the spectrograms. How can I solve this?

**Comment by JohannesSchwenzer** [comment]
Same here.
